apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/prometheus-community/helm-charts/'
    path: charts/prometheus
    targetRevision: 'prometheus-statsd-exporter-0.4.2'
  destination:
    namespace: prometheus
    server: 'https://kubernetes.default.svc'
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
